// Generated by https://quicktype.io

import { Coupon } from "../../../../Core/models/coupons/Coupon.models";

export interface CouponsDto {
  result:    Coupon[];
  isSuccess: boolean;
  message:   string;
}



