// Generated by https://quicktype.io

import { Coupon } from "../../../../Core/models/coupons/Coupon.models";

export interface CouponDto {
  result:    Coupon | null;
  isSuccess: boolean;
  message:   string;
}


